### PR TITLE
Use multiprocessing for PASTIS matrix calculation

### PR DESCRIPTION
**Pull request by ivalaginja**
Adresses #7 

I have adapted this from `hicat.scripts.stroke_minimization.calculate_jacobian`. Works fine, but want to test on full matrix before merging.

I also used this PR to clean up some configfile reading and directory creation.

### CODE REVIEW

**Comment by ivalaginja** [comment]
Hm, it worked fine on 5 segments, but gives me an error after the very last pair when using 120 segments:
Screen Shot 2019-11-25 at 19 44 45
[...]
Screen Shot 2019-11-25 at 19 42 50

It looks like it can't return the result from the pool. Not sure if it is too large or what is happening.

**Comment by mperrin** [comment]
The error text last line says that it’s trying to format something as an integer, specifically a 32 byte integer, but the value is outside the range supported by 32 bit integers.

**Comment by ivalaginja** [comment]
Yes, it seems like `multiprocess.pool` wants to do it as a 32bit integer, but my data is too large:
https://github.com/joblib/joblib/issues/818#issuecomment-445865581

In the link, they suggest using threads instead of processed. Alternatively, I could cut my data. I will have to look into this more thoroughly - if you have any ideas @mperrin, please let me know.

**Comment by mperrin** [comment]
I don’t think I understand yet what your code is doing well enough to comment without taking a closer look... Is that expected that it’s trying to return >2GB objects from each process? Or is it the set of all of them together that is >2GB? 

I have no experience using the threading backend they suggest. I don’t know if that would work well or not, but you could try it. 

Alternatively perhaps restructure your code so the returned values are not passed in memory but instead are written as temp files on disk and the filenames returned. That seems like an extra step we shouldn’t have to do but I expect it might be a work-around for this problem.

**Comment by mperrin** [comment]
Or, run two or more pools that each iterate only over part of the parameter space, so their returned data are smaller. Then combine together the outputs from the multiple pools. That’s probably simpler than adding in file output and input.

**Comment by ivalaginja** [comment]
A Stackoverflow user suggested this was fixed in Python 3.8:
https://stackoverflow.com/a/53368158/10112569

I am looking into this now.

**Comment by ivalaginja** [comment]
I set up an environment with Python 3.8 and get a different error message:

```bash
PAIR: 105-120
Calculating coro image...
Calculating mean contrast in dark hole
contrast: 2.3276463503564805e-10
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/connection.py", line 395, in _send_bytes
    self._send(pre_header)
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
/Users/ilaginja/anaconda/envs/patest/lib/python3.8/multiprocessing/resource_tracker.py:203: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I am dropping this, it's not worth investigating right now.

In case I pick this up at a later time, here are some notes:
- `jupyter` needs py < 3.8.0, which makes py3.8 essentially unusable for this repository since it relies heavily on jupyter notebooks. This would only be worth it if using py3.8 actually solves the above issue, which I don't know whether it does.
- to run PASTIS, I need `hcipy`, albeit still from an old commit that specifically requires `scipy` 1.2.1. This is not supported in py3.8, so there's another issue with that. I need to refactor the repo to use the most recent version of hcipy anyway (#4), which should fix that, but I am not there yet.
- if I still want to use hcipy from that specific commit, but in py3.8, I can keep the newer version of scipy, but need to manually add the following change in hcipy, plus remove the import of scipy at the top of that script:
https://github.com/ehpor/hcipy/commit/95dc7a661a4ddd0725def2a2ebf55e2024414c4d

I think the conclusion here is that I need to refactor the code for usage with hcipy and that I am dropping any multiprocessing for now.

**Comment by ivalaginja** [comment]
Created a cleaner draft PR of this in #24, closing this without merging.

**Pull request closed without merging**
